### ISSUE TITLE
MacOS library path

### ISSUE THREAD

**Issue by tpiselli** [gradle-guides/building-cpp-libraries#11]
On MacOS you'll need to change:
LD_LIBRARY_PATH=build/libs/greeter/shared/ ./build/exe/main/main
to:
export DYLD_LIBRARY_PATH=build/libs/greeter/shared/; ./build/exe/main/main
in order to get the following output:
Hello, Gradle User, your name has 11 chars.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #246](https://github.com/gradle/guides/issues/246) via [**ZenHub**](https://www.zenhub.com/)
