### ISSUE TITLE
Convert build to Kotlin DSL

### ISSUE THREAD

**Issue by eriwen** [gradle-guides/building-cpp-libraries#6]

**Comment by benignbala** [comment]
Should we not have both build.gradle and build.gradle.kts so that people can choose between the two ?

**Comment by eriwen** [comment]
The Kotlin DSL will not support the software model, so this guide will have to be significantly changed for new plugins sometime a long time from now.

**Comment by benignbala** [comment]
Do we create two separate branches till the time the software model is supported ? Or do we just flip this to the new style ? Also, are PRs welcome again ? Earlier, I did this specific guide with loads of guidance from @ysb33r when gradle started off the guides project. Thanks

**Comment by eriwen** [comment]
We only need to change the guide to use the [new C++ plugins](https://blog.gradle.org/introducing-the-new-cpp-plugins) that support the Kotlin DSL. The Kotlin DSL will _never_ support the software model as the software model is deprecated and will be removed in the future.

PRs are welcome for this, though I must admit I do not personally have a lot of time to provide guidance. Better to find guidance from others interested.

**Comment by benignbala** [comment]
@eriwen, I understand that the software model is deprecated and will be removed in the future. As of now, unfortunately, the official gradle user manual talks only about software model and so it makes sense that the official user manual and the guides that are linked to from the docs page are in sync. I think that we should retain this guide in the current form as long as there is a supported version of the Gradle community edition that supports the software model. It really doesn't matter that Kotlin is not going to support it. If Groovy supports it, then we need to have a version of this guide in the current form.

    But now, with the newer plugins (cpp-library, cpp-application), the way of doing it is different (and in some cases simpler). I believe I have a better understanding if the new way of doing things with the newer plugins. So, I might not specifically need guidance with this one. 

    The question is, do we create a new "building-cpp-libraries (new style)" guide ? Or, handle it differently ? Once we decide on that, I'll send in PRs sometime soon.

**Comment by lacasseio** [comment]
The guide was converted to use the new C++ plugin. There won't be any more reference to the software model.
