### ISSUE TITLE
Links should be updated to current documentation

### ISSUE THREAD

**Issue by dcabasson** [gradle-guides/building-cpp-libraries#8]
In the document:
https://guides.gradle.org/building-cpp-libraries/

The root for gradle documentation is:
https://docs.gradle.org/4.10-rc-2/

probably should be upgraded to:
https://docs.gradle.org/current/

**Comment by lacasseio** [comment]
We link to the documentation of the minimum supported Gradle version. It used to take the current wrapper version, now this information is modelled on the `guide` extension.
